services:
  webapi:
    image: phoneshopserver:1.0.3
    container_name: webapi
    build:
      context: .
      dockerfile: PhoneShopServer/Dockerfile    
    ports:
      - "7000:8080"     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
#      In order to connect project in Docker to Local MS SQL Server
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=DemoShopDB;User Id=sa;Password=root;TrustServerCertificate=true;

 
